### ISSUE TITLE
Keycloak logout not working when used with `next-auth`

### ISSUE THREAD

**Issue by woppers** [exlinc/keycloak-passport#2]
Hi, I was wondering if you could help me with the following issue please?

I'm trying to implement an authentication flow using [`next-auth`](https://github.com/iaincollins/next-auth/) and this `keycloak-passport` strategy.

Both libraries work great together when I log into my `keycloak` instance but when I log out, I seem to be logged out on the client side. But when I try to log in again using `keycloak-passport` I get the `Unable to sign in` page from [`next-auth`](https://github.com/iaincollins/next-auth/) 
![image](https://user-images.githubusercontent.com/3513149/44368297-4a32ea80-a4ca-11e8-8f22-2633b8d3cdbd.png)

It seems to be logging out from the client side but the session seems to be persisted on the server side. When I hit my login page directly it redirects me to the account admin section on my keycloak instance so I'm definitely still logged in on the server.

I've tried to debug the logout flow to see if I can determine the problem but none of the `console.log` statements I placed in the `handleSignOutSubmit()` function are firing.

I opened an issue on the `next-auth` repo [here](https://github.com/iaincollins/next-auth/issues/40) which goes into more detail. 

I'd be really grateful if you could point me in the tight direction on this please

**Comment by woppers** [comment]
@svarlamov Thanks a million for getting back to regarding this issue. I really appreciate it 🙂 I was hoping/praying that you may have some Jedi magic trick up your sleeve that would help me figure this out 😂 

Thanks for the advice. It's after narrowing down the search for the root problem. I'll keep digging into this and if/when I come up with a solution, you'll be the first to know 💪

**Comment by geekyme** [comment]
@woppers did you manage to figure out how to use nextjs with keycloak?

**Comment by Zembios** [comment]
@phillystafford @svarlamov Any progress on this issue?

**Comment by anthodb** [comment]
We have the same issue also here.. Any progress on this? The signout method from next-auth does not call the logout method of keycloak, resulting on a session still active on the server. The user is never asked again to enter the password. Which is critical for us after the signout. Thanks a lot for your input on this.
